spring.datasource.url =  jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

spring.datasource.username = ${PGUSER}
spring.datasource.password = ${PGPASSWORD}

spring.jpa.hibernate.ddl-auto = update

app.admin.usuario = ${APP_ADMIN_USUARIO}
app.admin.password = ${APP_ADMIN_PASSWORD}
app.cors.allowed-origins = ${APP_CORS_ALLOWED_ORIGINS}
app.cors.allowed-methods = GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers = Origin,Content-Type,Accept,Authorization
app.cors.allow-credentials = true
spring.jpa.show-sql = false

server.port = ${PORT:8080}