spring.application.name=backend

server.port=8080

app.cors.allowed-origins=http://localhost:4321,http://127.0.0.1:4321
app.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
app.cors.allowed-headers=Origin,Content-Type,Accept,Authorization
app.cors.exposed-headers=
app.cors.allow-credentials=true
app.cors.max-age=3600
